ALTER TABLE payroll ADD COLUMN IF NOT EXISTS pensionable_earnings NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE payroll ADD COLUMN IF NOT EXISTS pension_tier1 NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE payroll ADD COLUMN IF NOT EXISTS pension_tier2 NUMERIC(12,2) NOT NULL DEFAULT 0;
