ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS legal_name VARCHAR(160),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(40),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120),
  ADD COLUMN IF NOT EXISTS country VARCHAR(120) NOT NULL DEFAULT 'Ghana',
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(80) NOT NULL DEFAULT 'Africa/Accra',
  ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'GHS',
  ADD COLUMN IF NOT EXISTS work_week VARCHAR(32) NOT NULL DEFAULT 'Monday-Friday';
