const payrollRunUser = requireRole('admin'); if (!payrollRunUser) throw Error('redirect'); buildSidebar('payroll-runs');
const actions = { draft:['Calculate','calculate'], calculated:['Submit','submit'], pending_approval:['Approve','approve'], approved:['Finalize','finalize'], finalized:['Mark paid','mark_paid'] };
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function loadRuns(){const host=document.getElementById('run-rows');try{const runs=await api.get('/payroll/runs');host.innerHTML=runs.length?runs.map(run=>{const action=actions[run.status];return `<tr><td>${esc(run.period_start)} – ${esc(run.period_end)}</td><td>${esc(run.pay_group_name)}</td><td>${esc(run.country_code)}</td><td>${fmt.statusBadge(String(run.status).replace('_',' '))}</td><td>${action?`<button class="btn btn-primary btn-sm" onclick="advanceRun(${run.id},'${action[1]}')">${action[0]}</button>`:'Complete'}</td></tr>`}).join(''):'<tr><td colspan="5">No payroll runs yet.</td></tr>';}catch(error){host.innerHTML=`<tr><td colspan="5">${esc(error.message)}</td></tr>`;}}
async function createRun(){try{const setup=await api.get('/payroll/setup');const group=setup.pay_groups?.[0];if(!group)throw Error('No active pay group is available');const month=new Date(),start=new Date(month.getFullYear(),month.getMonth(),1).toISOString().slice(0,10),end=new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.innerHTML=`<div class="modal" style="max-width:520px"><div class="modal-header"><h3>Create payroll run</h3><button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button></div><div class="modal-body"><div class="run-dialog-note">This creates a draft only. You will review it before calculation.</div><div class="run-dialog-summary"><div><span>Pay group</span><strong>${esc(group.name)}</strong></div><div><span>Period</span><strong>${start} – ${end}</strong></div></div></div><div class="modal-footer"><button class="btn btn-outline" onclick="this.closest('.modal-overlay').remove()">Cancel</button><button class="btn btn-primary" onclick="confirmCreateRun(this,${group.id},'${start}','${end}')">Create draft</button></div></div>`;document.body.appendChild(overlay);}catch(error){toast(error.message||'Could not create payroll run','error');}}
async function confirmCreateRun(button,groupId,start,end){try{button.disabled=true;button.textContent='Creating…';await api.post('/payroll/runs',{pay_group_id:groupId,period_start:start,period_end:end,payment_date:end});button.closest('.modal-overlay').remove();toast('Draft payroll run created','success');loadRuns();}catch(error){button.disabled=false;button.textContent='Create draft';toast(error.message||'Could not create payroll run','error');}}
async function advanceRun(id,action){const label=actions[Object.keys(actions).find(key=>actions[key][1]===action)]?.[0]||action;const note=action==='finalize'?'Finalized outputs are locked.':'This action changes the payroll run stage.';const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.innerHTML=`<div class="modal" style="max-width:480px"><div class="modal-header"><h3>${label} payroll run</h3><button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button></div><div class="modal-body"><div class="run-dialog-note">${note}</div></div><div class="modal-footer"><button class="btn btn-outline" onclick="this.closest('.modal-overlay').remove()">Cancel</button><button class="btn btn-primary" onclick="confirmRunAction(this,${id},'${action}')">${label}</button></div></div>`;document.body.appendChild(overlay);}
async function confirmRunAction(button,id,action){try{button.disabled=true;button.textContent='Saving…';if(action==='calculate')await api.post(`/payroll/runs/${id}/calculate`);else await api.post(`/payroll/runs/${id}/transition`,{action});button.closest('.modal-overlay').remove();toast('Payroll run updated','success');loadRuns();}catch(error){button.disabled=false;toast(error.message||'Could not update payroll run','error');}}
loadRuns();
